import { readdir, readFile, writeFile, mkdir } from 'fs/promises';
import { join, relative } from 'path';

const DIST_DIR = join(import.meta.dir, '..', 'dist');
const OUTPUT_FILE = join(import.meta.dir, '..', 'src', 'embedded-assets.ts');

async function getAllFiles(dir: string): Promise<string[]> {
	const files: string[] = [];
	const entries = await readdir(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await getAllFiles(fullPath)));
		} else {
			files.push(fullPath);
		}
	}

	return files;
}

async function main() {
	console.log('Embedding assets from dist/ into src/embedded-assets.ts...');

	const files = await getAllFiles(DIST_DIR);
	const assets: Record<string, { content: string; mimeType: string }> = {};

	const mimeTypes: Record<string, string> = {
		'.html': 'text/html',
		'.css': 'text/css',
		'.js': 'application/javascript',
		'.json': 'application/json',
		'.png': 'image/png',
		'.jpg': 'image/jpeg',
		'.jpeg': 'image/jpeg',
		'.gif': 'image/gif',
		'.svg': 'image/svg+xml',
		'.ico': 'image/x-icon',
		'.woff': 'font/woff',
		'.woff2': 'font/woff2',
	};

	for (const filePath of files) {
		const relativePath = '/' + relative(DIST_DIR, filePath);
		const ext = filePath.substring(filePath.lastIndexOf('.'));
		const mimeType = mimeTypes[ext] || 'application/octet-stream';

		const content = await readFile(filePath);
		const base64 = content.toString('base64');

		assets[relativePath] = { content: base64, mimeType };
		console.log(`  Embedded: ${relativePath} (${mimeType})`);
	}

	const output = `// Auto-generated file - do not edit manually
// Generated by scripts/embed-assets.ts

export const embeddedAssets: Record<string, { content: string; mimeType: string }> = ${JSON.stringify(assets, null, '\t')};

export function getAsset(path: string): { data: ArrayBuffer; mimeType: string } | null {
	const asset = embeddedAssets[path];
	if (!asset) return null;

	const binary = atob(asset.content);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i++) {
		bytes[i] = binary.charCodeAt(i);
	}

	return { data: bytes.buffer as ArrayBuffer, mimeType: asset.mimeType };
}
`;

	await writeFile(OUTPUT_FILE, output);
	console.log(`\nGenerated: ${OUTPUT_FILE}`);
	console.log(`Total assets: ${Object.keys(assets).length}`);
}

main().catch(console.error);